### ISSUE TITLE
這行得到的是左值？

### ISSUE THREAD

**Issue by Brli** [legnaleurc/khopper#36]
https://github.com/legnaleurc/khopper/blob/master/core/src/album/album.cpp#L74
key.get() 在我嘗試把軟體弄到 Qt5 會報錯
>error: invalid initialization of reference of type ‘const QUrl&’ from expression of type ‘const >khopper::album::Album*’
>  return ::qHash( key.get() );
>                         ^
似乎跟 qHash 在 Qt5 有改版有關
求解？

**Comment by Brli** [comment]
btw, the patch
[Uploading 0001-try-to-port-to-qt5.txt…]()

**Comment by legnaleurc** [comment]
```cpp
#include <QtCore/QHash>
```

即可

Qt5 port 好像沒有我想像中單純，因為要拔掉 Phonon，FFmpeg 可能也需要更新一下
